AirBnbUdC.GUI/Controllers/Parameters/PropertyController.cs
using AirbnbUdc.Application.Implementation.Implementation.Parameters;
using AirbnbUdC.Application.Contracts.Contracts.Parameters;
using AirbnbUdC.Application.Contracts.DTO.Parameters;
using AirBnbUdC.GUI.Mappers.Parameters;
using AirBnbUdC.GUI.Models.Parameters;
using AirBnbUdC.GUI.Models.ReportModels;
using Microsoft.Reporting.WebForms;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace AirBnbUdC.GUI.Controllers.Parameters
{
    public class PropertyController : Controller
    {
        private IPropertyApplication app;
        private ICityApplication cityApp;
        private IPropertyOwnerApplication propertyOwnerApp;

        public PropertyController(IPropertyApplication PropertyImplementationApp, ICityApplication CityImplementationApp, IPropertyOwnerApplication PropertyOwnerImplementationApp)
        {
            this.app = PropertyImplementationApp;
            this.cityApp = CityImplementationApp;
            this.propertyOwnerApp = PropertyOwnerImplementationApp;
        }

        PropertyMapperGUI mapper = new PropertyMapperGUI();
        // GET: Property
        public ActionResult Index(string filter = "")
        {
            var list = mapper.MapperT1toT2(app.GetAllRecords(filter));
            return View(list);
        }

        // GET: Property/Details/5
        public ActionResult Details(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PropertyModel propertyModel = mapper.MapperT1toT2(app.GetRecord(id));
            if (propertyModel == null)
            {
                return HttpNotFound();
            }
            return View(propertyModel);
        }

        // GET: Property/Create
        public ActionResult Create()
        {
            PropertyModel model = new PropertyModel();
            FillListForView(model);
            return View(model);
        }

        private void FillListForView(PropertyModel model)
        {
            CityMapperGUI cityMapper = new CityMapperGUI();
            model.CityList = cityMapper.MapperT1toT2(cityApp.GetAllRecords(string.Empty));

            PropertyOwnerMapperGUI propertyOwnerMapper = new PropertyOwnerMapperGUI();
            model.PropertyOwnerList = propertyOwnerMapper.MapperT1toT2(propertyOwnerApp.GetAllRecords(string.Empty));
        }

        // POST: Property/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PropertyModel propertyModel)
        {
            ModelState.Remove("City.Name");
            ModelState.Remove("City.Country");
            ModelState.Remove("PropertyOwner.FirstName");
            ModelState.Remove("PropertyOwner.FamilyName");
            ModelState.Remove("PropertyOwner.Email");
            ModelState.Remove("PropertyOwner.Cellphone");
            ModelState.Remove("PropertyOwner.Photo");
            if (ModelState.IsValid)
            {
                PropertyDTO propertyDTO = mapper.MapperT2toT1(propertyModel);
                app.CreateRecord(propertyDTO);
                return RedirectToAction("Index");
            }
            return View(propertyModel);
        }

        // GET: Property/Edit/5
        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PropertyModel propertyModel = mapper.MapperT1toT2(app.GetRecord(id));
            if (propertyModel == null)
            {
                return HttpNotFound();
            }
            FillListForView(propertyModel);
            return View(propertyModel);
        }

        // POST: Property/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PropertyModel propertyModel)
        {
            ModelState.Remove("City.Name");
            ModelState.Remove("City.Country");
            ModelState.Remove("PropertyOwner.FirstName");
            ModelState.Remove("PropertyOwner.FamilyName");
            ModelState.Remove("PropertyOwner.Email");
            ModelState.Remove("PropertyOwner.Cellphone");
            ModelState.Remove("PropertyOwner.Photo");
            if (ModelState.IsValid)
            {
                PropertyDTO propertyDTO = mapper.MapperT2toT1(propertyModel);
                app.UpdateRecord(propertyDTO);
                return RedirectToAction("Index");
            }
            return View(propertyModel);
        }

        // GET: Property/Delete/5
        public ActionResult Delete(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PropertyModel propertyModel = mapper.MapperT1toT2(app.GetRecord(id));
            if (propertyModel == null)
            {
                return HttpNotFound();
            }
            return View(propertyModel);
        }

        // POST: Property/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            app.DeleteRecord(id);
            return RedirectToAction("Index");
        }

        public ActionResult GenerateReport(string format = "PDF")
        {
            var list = app.GetAllRecords(string.Empty);
            PropertyMapperGUI propertyMapperGUI = new PropertyMapperGUI();
            List<PropertiesByCityReportModel> recordsList = new List<PropertiesByCityReportModel>();

            foreach (var property in list)
            {
                recordsList.Add(
                    new PropertiesByCityReportModel()
                    {
                        Id = property.Id.ToString(),
                        PropertyAddress = property.PropertyAddress,
                        CityId = property.City.Id.ToString(),
                        CustomerAmount = property.CustomerAmount.ToString(),
                        Price = property.Price.ToString(),
                        Latitude = property.Latitude,
                        Longitude = property.Longitude,
                        PropertyOwnerId = property.PropertyOwner.Id.ToString(),
                        CheckinData = property.CheckinData.ToString(),
                        CheckoutData = property.CheckoutData.ToString(),
                        Details = property.Details,
                        Pets = property.Pets.ToString(),
                        Freezer = property.Freezer.ToString(),
                        LaundryService = property.LaundryService.ToString(),
                        CityName = property.City.Name,
                        PropertyOwnerFirstName = property.PropertyOwner.FirstName,
                        PropertyOwnerFamilyName = property.PropertyOwner.FamilyName
                    });
            }

            string reportPath = Server.MapPath("~/Reports/RdlcFiles/PropertiesByCityReport.rdlc");
            //List<string> dataSets = new List<string> { "CustomerList" };
            LocalReport lr = new LocalReport();

            lr.ReportPath = reportPath;
            lr.EnableHyperlinks = true;

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;
            string mimeType, encoding, fileNameExtension;

            ReportDataSource datasource = new ReportDataSource("PropertiesByCityDataSet", recordsList);
            lr.DataSources.Add(datasource);


            renderedBytes = lr.Render(
            format,
            string.Empty,
            out mimeType,
            out encoding,
            out fileNameExtension,
            out streams,
            out warnings
            );

            return File(renderedBytes, mimeType);
        }
    }
}

AirBnbUdC.GUI/Controllers/ViewsController/HomePropertyController.cs
using AirbnbUdC.Application.Contracts.Contracts.Parameters;
using AirBnbUdC.GUI.Mappers.Parameters;
using AirBnbUdC.GUI.Models.Parameters;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AirBnbUdC.GUI.Controllers.ViewsController
{
    public class HomePropertyController : Controller
    {
        private IPropertyApplication appProperty;
        private IPropertyMultimediaApplication appPropertyMultimedia;

        public HomePropertyController(IPropertyApplication PropertyImplementationApp, IPropertyMultimediaApplication PropertyMultimediaImplementationApp)
        {
            this.appProperty = PropertyImplementationApp;
            this.appPropertyMultimedia = PropertyMultimediaImplementationApp;
        }

        PropertyMapperGUI mapperProperty = new PropertyMapperGUI();
        PropertyMultimediaMapperGUI mapperPropertyMultimedia = new PropertyMultimediaMapperGUI();

        // GET: HomePropertyModels
        public ActionResult Index(string filter = "")
        {
            List<HomePropertyModel> listHomeProperty = new List<HomePropertyModel>();

            var listProperty = mapperProperty.MapperT1toT2(appProperty.GetAllRecords(filter));
            var listPropertyMultimedia = mapperPropertyMultimedia.MapperT1toT2(appPropertyMultimedia.GetAllRecords(filter));

            foreach (var itemProperty in listProperty)
            {
                HomePropertyModel itemHomeProperty = new HomePropertyModel();
                itemHomeProperty.Id = itemProperty.Id;
                itemHomeProperty.PropertyAddress = itemProperty.PropertyAddress;
                itemHomeProperty.CityName = itemProperty.City.Name;
                itemHomeProperty.CustomerAmount = itemProperty.CustomerAmount;
                itemHomeProperty.Price = itemProperty.Price;
                itemHomeProperty.MultimediaLinks = new List<string>();
                foreach (var itemPropertyMultimedia in listPropertyMultimedia)
                {
                    if (itemProperty.Id == itemPropertyMultimedia.Property.Id)
                    {
                        itemHomeProperty.MultimediaLinks.Add(itemPropertyMultimedia.MultimediaLink);
                    }
                }
                listHomeProperty.Add(itemHomeProperty);
            }

            return View(listHomeProperty);
        }
    }
}

AirBnbUdC.GUI/Views/HomeProperty/Index.cshtml
@model IEnumerable<AirBnbUdC.GUI.Models.Parameters.HomePropertyModel>

<main>
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">AirBnb</h1>
            <p class="lead text-muted">Pertenece a cualquier lugar</p>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <div id="carousel-@item.Id" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    @foreach (var multimediaLink in item.MultimediaLinks)
                                    {
                                        <div class="carousel-item @(multimediaLink == item.MultimediaLinks.First() ? "active" : "")">
                                            <img class="d-block w-100" src="@multimediaLink" alt="Imagen Propiedad">
                                        </div>
                                    }
                                </div>
                                <a class="carousel-control-prev" href="#carousel-@item.Id" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                </a>
                                <a class="carousel-control-next" href="#carousel-@item.Id" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(modelItem => item.CityName)</h5>
                                <p class="card-text">
                                    <strong>Dirección:</strong> @Html.DisplayFor(modelItem => item.PropertyAddress) <br>
                                    <strong>Capacidad:</strong> @Html.DisplayFor(modelItem => item.CustomerAmount)
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        @Html.ActionLink("Detalles", "Details", "Property", new { id = item.Id }, new { @Class = "btn btn-sm btn-outline-secondary" })
                                    </div>
                                    <small class="text-dark font-weight-bold" style="font-size: 1.5em; color: navy;">
                                        $@Html.DisplayFor(modelItem => item.Price)
                                    </small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</main>

@section Scripts {
    <script>
        // Desactivar el desplazamiento automático del carrusel
        $(document).ready(function () {
            $('.carousel').carousel({
                interval: false
            });

            // Manejar la navegación manual al hacer clic en los botones "Next" y "Previous"
            $('.carousel-control-prev').on('click', function () {
                $(this).closest('.carousel').carousel('prev');
            });

            $('.carousel-control-next').on('click', function () {
                $(this).closest('.carousel').carousel('next');
            });
        });
    </script>
}